### ISSUE TITLE
EAPI=7 support

### ISSUE THREAD

**Issue by MageSlayer** [MageSlayer/paludis-gentoo-patches#6]
Corresponding Gentoo bug https://bugs.gentoo.org/655976

**Comment by Bfgeshka** [comment]
Can this feature be expected anytime soon? It's probably the last thing that obstructs paludis usage.

Btw, I've rehosted your ebuild in my overlay (which is available in official listings), I hope you don't mind.

**Comment by MageSlayer** [comment]
Yes, I understand.
I had time to only investigate design for EAPI7 so far, unfortunately.

Sure, I don't mind.

**Comment by bodograumann** [comment]
The changes from EAPI 6 to EAPI 7 can be found in [The ultimate guide to EAPI 7](https://dev.gentoo.or/~mgorny/articles/the-ultimate-guide-to-eapi-7.html).
I think we only need partial support to make paludis completely usable again.

- Banned commands and removed variables
    Can be ignored for now.

- Improved cross-compilation support
    Not sure if there is any support currently in paludis.
    I think it would suffice to merge `BDEPEND` into `DEPEND` for now.

- Version manipulation and comparison commands
    We need to implement the three new functions `ver_cut`, `ver_rs` and `ver_test`.
    The guide says there is `eapi7-ver.eclass` ”providing the reference implementation for previous EAPIs”.
    Maybe we can rely on that for now?

- Other new features and commands
    - `eqawarn` needs to be defined, but need not do anything. Also there is a fallback implementation in `eutils.eclass`.
    - `ENV_UNSET` is needed. This should not be too hard to implement.
    - `dostrip`, if I understand it correctly, could be implemented simplified by still having it disabling stripping completely and ignoring `dostrip -x`.
    - We need to depend on `>=patch-2.7`.

- Other behaviour changes
    - We need to remove the trailing slash of `D`, `ED`, `ROOT` and `EROOT`.
    - The output of `einfo`, `elog`, etc. must not go to stdout anymore.
    - `die` and `assert` need to be usable in subshells. Is this already the case?
    - `nonfatal` must be available as a shell function and as an external command. What do we currently have?
    - Make `domo` ignore the prefix, just like `dodoc` etc.
    - `|| ()` and `^^ ()` dependencies should count as not satisfied. I don’t think this is too important for now.

- Profile changes
    - Directories in profiles are probably not widely used right now and still forbidden in the main gentoo repo. So this can be postponed.
    - Ignoring `package.provided` is also not that important.


So all in all it seems there are only a few changes necessary to get to a working state with basic EAPI 7 support.

Unfortunately I don’t think I can be of much help in implementing, as I’m completely unfamiliar with the codebase and I haven’t used c++ in years. If there is something to test though, I'll gladly try to do that.

**Comment by MageSlayer** [comment]
My own conclusions about EAPI7 are roughly the same.
I'll try to start doing some concrete steps.

**Comment by MageSlayer** [comment]
For those interested (read - those who are ready for testing/breakage).

I've pushed new ebuild changes in https://github.com/MageSlayer/paludis-gentoo-overlay with "eapi7" use flag to enable _experimental_ EAPI7 Paludis build.

**Comment by hlandgarten** [comment]
I am getting a lot of failures on EAPI 7 ebuilds like this one in xterm-337:
!!! ERROR in x11-terms/xterm-337::gentoo:
!!! In inherit at line 63
!!! Error finding eclass desktop

All the errors reference different eclasses but mostly: autotools, mulitlib, multili-minimal. and distutils-r1

All the failures occur in:  /usr/libexec/paludis/0/eclass_functions.bash:63

**Comment by MageSlayer** [comment]
@hlandgarten 
Yes, I am aware of it.
That's due to improper ECLASSDIR/ECLASSDIRS removal.
I'll fix it asap.

**Comment by hlandgarten** [comment]
Most install now. Still have issue on some ebuilds. For example rdesktop:
!!! ERROR in net-misc/rdesktop-1.8.3-r3::gentoo:
!!! In has_version at line 2464
!!! /usr/libexec/paludis/ebuild.bash should take exactly one arg

All the ebuilds with this issue have multiple items in the inherit line.

**Comment by MageSlayer** [comment]
Ok. Thanks for testing.
New EAPI7 "has_version" support is yet to be implemented.

**Comment by hlandgarten** [comment]
I currently have 20 ebuilds failing because of has_version so it would be good to get it implemented. Gentoo added lots of EAPI7 ebuilds.

**Comment by MageSlayer** [comment]
Yes, I know.
I'll implement it as soon as I have some free time.

**Comment by kdudka** [comment]
I have also seen the `has_version` related error mentioned above:
```
!!! ERROR in dev-libs/libevdev-1.5.9-r1::gentoo:
!!! In has_version at line 2202
!!! /usr/libexec/paludis/ebuild.bash should take exactly one arg

!!! Call stack:
!!!    * has_version (/var/tmp/paludis/dev-libs-libevdev-1.5.9-r1/temp/loadsaveenv:2202)
!!!    * python_is_installed (/var/tmp/paludis/dev-libs-libevdev-1.5.9-r1/temp/loadsaveenv:3646)
!!!    * _python_EPYTHON_supported (/var/tmp/paludis/dev-libs-libevdev-1.5.9-r1/temp/loadsaveenv:670)
!!!    * python_setup (/var/tmp/paludis/dev-libs-libevdev-1.5.9-r1/temp/loadsaveenv:3793)
!!!    * python-any-r1_pkg_setup (/var/tmp/paludis/dev-libs-libevdev-1.5.9-r1/temp/loadsaveenv:3119)
!!!    * pkg_setup (/var/tmp/paludis/dev-libs-libevdev-1.5.9-r1/temp/loadsaveenv:3069)
!!!    * ebuild_f_setup (/usr/libexec/paludis/0/pkg_setup.bash:43)
!!!    * ebuild_main (/usr/libexec/paludis/ebuild.bash:675)
!!!    * main (/usr/libexec/paludis/ebuild.bash:698)
```

Besides that, it seems to work fine so far.  Thank you for the progress on this!

**Comment by MageSlayer** [comment]
Glad someone else also appreciates this project.

**Comment by hlandgarten** [comment]
The new version is working great. All my ebuilds are now building. Thank you for bringing paludis back to life. Maybe we can get it back in the gentoo tree.

**Comment by MageSlayer** [comment]
@hlandgarten 
Please beware, "best_version" and "has_version" are merely stubs doing nothing except pretending as working. Proper version is in progress.

**Comment by kdudka** [comment]
The `has_version` related error went away and everything seems to work fine.  Thank you for working on this!

**Comment by Ionic** [comment]
Anyone using this branch should be aware that due to missing `BDEPEND` support, package ordering may be wrong (which is a bit disconcerting) and builds can either fail due to missing build-time dependencies or features disabled, depending on how flexible the build system is.

**Comment by hlandgarten** [comment]
firefox-66.0-r1 will not compile with paludis. It compiles fine with portage. The failure comes at the start of the compile phase showing an autoconf issue. The real issue is that we are getting corruption in the PATH assignment is various config files. The source of the problem is loadsaveenv file in the temp directory which shows
PATH=$' \E[32;01m*\E[0m Will use LLVM slot 8!\n/usr/lib/llvm/8/bin:/var/tmp/paludis/www-client-firefox-66.0-r1/temp//python3.6/bin:/usr/libexec/paludis/utils/0:/usr/libexec/paludis/utils/1:/usr/libexec/paludis/utils/2:/usr/libexec/paludis/utils/3:/usr/libexec/paludis/utils/4:/usr/libexec/paludis/utils/5:/usr/libexec/paludis/utils/6:/usr/libexec/paludis/utils:/usr/bin:/usr/sbin:/bin:/sbin:/usr/lib/llvm/8/bin:/usr/lib/llvm/7/bin:/usr/lib/llvm/6/bin:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/opt/vmware/bin:/opt/cuda/bin:/opt/cuda/libnvvp'

The \E[32;01m*\E[0m Will use LLVM slot 8!\n string should not be there and if manually removed before config phase the build completes.

**Comment by MageSlayer** [comment]
@hlandgarten 
I guess it has nothing to do with EAPI7, so I've created a separate issue https://github.com/MageSlayer/paludis-gentoo-patches/issues/15

**Comment by hasufell** [comment]
How well is EAPI=7 supported at this point?

**Comment by MageSlayer** [comment]
Try and see yourself :)
Most stuff works.

**Comment by hasufell** [comment]
> Try and see yourself :)
> Most stuff works.

I would prefer to have a list of supported, unsupported features and known bugs, before I allow a PM to touch my root file system and package database.

**Comment by MageSlayer** [comment]
I would prefer it too.

**Comment by hasufell** [comment]
> I would prefer it too.

So you don't know what you implemented and what you didn't implement?

**Comment by Ionic** [comment]
It's a bit difficult to tell what exactly is supported and what isn't.

Most stuff is implemented and I think that using paludis won't necessarily break your system. However, some edges are rough and it won't do "the right thing"™.

Some stuff that I *know* is missing:
  - `eqawarn` (non-critical, this is used to display developer warnings and this function missing should not cause the build to abort or behave erratically)
  - proper handling of `BDEPENDS`. Currently, those are just merged into `DEPENDS`, which factually is wrong. That won't cause harm (per se), but might lead to unnecessary builds of dependencies for unneeded architectures. Packages in `BDEPENDS` need only be available for the host architecture according to PMS, so that they can be executed natively on the system, while packages in `DEPENDS` need to be available in both target and host architectures.
  - new options for `{has,best}_version` are currently only stubbed out IIRC and will scan for the packages in the default root location only.
  - optional parameter to `dostrip` to exclude binaries from being stripped
  - `ENV_UNSET` support used to unset variables, e.g. via a whole profile

Some stuff I figure is still missing:
  - changes to `domo`
  - `nonfatal` both as function and external command
  - `die` and `assert` in subshells(?) Not sure if that didn't always work with paludis, but it's possible that it didn't so would need to change for EAPI 7.
  - `--with-sysroot` support automatically passed by `econf`? Maybe paludis already does that, maybe not.


I have missed some points. Is that good enough for you? Most unimplemented stuff is either non-critical, only really useful for cross-compilation and won't affect host builds or will make packages behave slightly wrong (like failing the build due to `XDG_*` stuff being set or not excluding specific binaries from being stripped).
